### ISSUE TITLE
Missing dependencies and more

### ISSUE THREAD

**Issue by domenicoMuscill0** [wangqinsi1/MathNAS#3]
Hi, i was trying to reproduce the results using Google Colab ([here](https://colab.research.google.com/drive/1JHjWh-G4dK8p4sGtWCA1nW3BNzsEMkgr#offline=true&sandboxMode=true)) i faced many minor problems:

1. It was not specified to add timm and yacs in the installation procedure
2. I get tracebacks while running nasvit because the file "MathNAS/valide/NASViT/misc/attentive_nas_eval.py" is malformed (a for istruction without proper indentation at line 34)
3. Running main.py in nas mode on nasbench201 gives a predicted accuracy of 11.5% with this architecture "|avg_pool_3x3\~0|+|avg_pool_3x3\~0|avg_pool_3x3\~1|+|avg_pool_3x3\~0|avg_pool_3x3\~1|avg_pool_3x3\~2|" whichever latency and energy constraint i add and with every gpu type i choose. 
4. I cannot predict the accuracy of the supertransformer on raspberrypi since there is an error with the list indexing performed at line 26 of MathNAS/predict.py

**Comment by Ah-miu** [comment]
Hi, thank you for your interest in MathNAS and for attempting to reproduce our results. We appreciate you bringing these four issues to our attention. We have made the corresponding modifications to address them and have validated the changes in a new environment. If you encounter any further problems, please feel free to reach out to us. :)
